server:
  port: 8080
spring:
  profiles:
    active: druid
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://47.96.158.220:13306/study?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
          username: root
          password: "@123lmyLMY."
          driver-class-name: com.mysql.cj.jdbc.Driver
        lmy:
          url: jdbc:mysql://localhost:3306/study?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
          username: root
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.baomidou: debug


##自定义文档目录
#knife4j:
#  markdowns: classpath:markdown/*
