server:
  port: 80

mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.huize.migrationcommon.entity
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    # 若不开启，则使用map接收查询结果的时候会过滤掉null的列，进而导致结果集的数量有误（针对map接收结果集的情况）
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto

spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
    dynamic:
      #      SQL性能分析插件
      p6spy: false
      druid:
        filters: stat
      datasource:
        master:
          url: jdbc:mysql://47.96.158.220:13306/migration?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
          username: root
          password: "@123lmyLMY."
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 1
            max-active: 2
        mysql_reader:
          url: jdbc:mysql://47.96.158.220:13306/study?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
          username: root
          password: "@123lmyLMY."
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 1
            max-active: 2
        mysql_writer:
          url: jdbc:mysql://localhost:3306/study?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
          username: root
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 2
logging:
  level:
    com.baomidou: debug
    root: info
    com.huize: debug

# 若invoker实现类没有加入spring容器，则可以通过配置的方式来扫描所有的invoker实现类
filter:
  basepkg: com.swust


##自定义文档目录
#knife4j:
#  markdowns: classpath:markdown/*
